const listings = [
  {
    title: "Cozy Place downtown!",
    city: "San Diego",
    type: "entire-place",
    price: 138,
    img: "img/sd/cozy.jpeg",
  },
  {
    title: "Modern Shared Abode",
    city: "Lake Tahoe",
    type: "shared-room",
    price: 95,
    img: "img/lt/modern.jpeg",
  },
  {
    title: "Updated Cozy Apartment",
    city: "Chicago",
    type: "private-room",
    price: 200,
    img: "img/chicago/view.jpeg",
  },
  {
    title: "Vintage Family Home",
    city: "Lake Tahoe",
    type: "private-room",
    price: 129,
    img: "img/lt/vintage.jpeg",
  },
  {
    title: "Mansion with a Pool",
    city: "San Diego",
    type: "entire-place",
    price: 500,
    img: "img/sd/luxury.jpeg",
  },
  {
    title: "Southside Family Estate",
    city: "Chicago",
    type: "entire-place",
    price: 670,
    img: "img/chicago/country.jpeg",
  },
  {
    title: "Tiny Cabin",
    city: "Lake Tahoe",
    type: "entire-place",
    price: 225,
    img: "img/lt/tiny.jpeg",
  },
  {
    title: "Stunning Lakeside House",
    city: "Lake Tahoe",
    type: "entire-place",
    price: 950,
    img: "img/lt/lakeside.jpeg",
  },
  {
    title: "Room in Luxury Tower",
    city: "San Diego",
    type: "shared-room",
    price: 98,
    img: "img/sd/highrise.jpeg",
  },
  {
    title: "Beach views",
    city: "San Diego",
    type: "entire-place",
    price: 400,
    img: "img/sd/ocean.webp",
  },
  {
    title: "Cozy Tahoe Cabin",
    city: "Lake Tahoe",
    type: "entire-place",
    price: 450,
    img: "img/lt/cozy.jpeg",
  },
  {
    title: "High Rise Luxury Hotel",
    city: "Chicago",
    type: "private-room",
    price: 360,
    img: "img/chicago/luxe.jpeg",
  },
  {
    title: "Urban Desert Bungalow",
    city: "San Diego",
    type: "private-room",
    price: 500,
    img: "img/sd/urban.webp",
  },
  {
    title: "Entire Penthouse",
    city: "San Diego",
    type: "entire-place",
    price: 999,
    img: "img/sd/penthouse.jpeg",
  },
  {
    title: "Philo Hideaway",
    city: "Chicago",
    type: "shared-room",
    price: 89,
    img: "img/chicago/simple.jpeg",
  },
  {
    title: "Sunny Chicago Bungalow",
    city: "Chicago",
    type: "entire-place",
    price: 350,
    img: "img/chicago/sunny.jpeg",
  },
  {
    title: "Hotel with Park View",
    city: "Chicago",
    type: "private-room",
    price: 279,
    img: "img/chicago/modern.jpeg",
  },
  {
    title: "Green A Frame",
    city: "Lake Tahoe",
    type: "entire-place",
    price: 350,
    img: "img/lt/green.jpeg",
  },
];
